# Generated by Django 6.0.4 on 2026-04-26 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Адрес канала"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "avatar_small",
                    models.ImageField(
                        upload_to="channels/avatars/small/",
                        verbose_name="Аватар (урезанный)",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        upload_to="channels/avatars/original/", verbose_name="Аватар"
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        upload_to="channels/banners/original/", verbose_name="Баннер"
                    ),
                ),
                (
                    "banner_small",
                    models.ImageField(
                        upload_to="channels/banners/small/",
                        verbose_name="Баннер (урезанный)",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="channels",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец канала",
                    ),
                ),
            ],
            options={
                "verbose_name": "Канал",
                "verbose_name_plural": "Каналы",
            },
        ),
    ]
